load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "SuperSecret",
    srcs = glob(["**/*.swift"]),
    module_name = "SuperSecret",
    tags = ["manual"],
    visibility = ["//visibility:public"],
)
